# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='landing_page.UserInfo')),
                ('inspector1', models.CharField(choices=[('0', 'inspect_A'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1)),
                ('inspector2', models.CharField(choices=[('0', 'inspect_A'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1)),
                ('inspector3', models.CharField(choices=[('0', 'inspect_A'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1)),
                ('lender1', models.CharField(choices=[('0', 'lender_A'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1)),
                ('lender2', models.CharField(choices=[('0', 'lender_A'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1)),
                ('lender3', models.CharField(choices=[('0', 'lender_A'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1)),
                ('closingco1', models.CharField(choices=[('0', 'closingco_A'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1)),
                ('closingco2', models.CharField(choices=[('0', 'closingco_A'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1)),
                ('closingco3', models.CharField(choices=[('0', 'closingco_A'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1)),
            ],
        ),
    ]
