# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_num', models.AutoField(primary_key=True, serialize=False)),
                ('contract_view', models.URLField()),
                ('file_view', models.URLField()),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('parties', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=15, null=True)),
                ('buyer_closing_location', models.CharField(max_length=200, null=True)),
                ('seller_delivery_property', models.DateTimeField(null=True)),
                ('seller_order_provide_purchase_title_deadline', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('inspector1', models.CharField(choices=[('0', 'BPG Home Inspectors'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1)),
                ('inspector2', models.CharField(choices=[('0', 'BPG Home Inspectors'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1)),
                ('inspector3', models.CharField(choices=[('0', 'BPG Home Inspectors'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1)),
                ('lender1', models.CharField(choices=[('0', 'USA Mortgage'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1)),
                ('lender2', models.CharField(choices=[('0', 'USA Mortgage'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1)),
                ('lender3', models.CharField(choices=[('0', 'USA Mortgage'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1)),
                ('closingco1', models.CharField(choices=[('0', 'Investors Title'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1)),
                ('closingco2', models.CharField(choices=[('0', 'Investors Title'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1)),
                ('closingco3', models.CharField(choices=[('0', 'Investors Title'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
