# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='closingco1',
            field=models.CharField(choices=[('0', 'Investors Title'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='closingco2',
            field=models.CharField(choices=[('0', 'Investors Title'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='closingco3',
            field=models.CharField(choices=[('0', 'Investors Title'), ('1', 'closingco_B'), ('2', 'closingco_C'), ('3', 'closingco_D'), ('4', 'closingco_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='inspector1',
            field=models.CharField(choices=[('0', 'BPG Home Inspectors'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='inspector2',
            field=models.CharField(choices=[('0', 'BPG Home Inspectors'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='inspector3',
            field=models.CharField(choices=[('0', 'BPG Home Inspectors'), ('1', 'inspect_B'), ('2', 'inspect_C'), ('3', 'inspect_D'), ('4', 'inspect_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='lender1',
            field=models.CharField(choices=[('0', 'USA Mortgage'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='lender2',
            field=models.CharField(choices=[('0', 'USA Mortgage'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='lender3',
            field=models.CharField(choices=[('0', 'USA Mortgage'), ('1', 'lender_B'), ('2', 'lender_C'), ('3', 'lender_D'), ('4', 'lender_E')], max_length=1),
        ),
    ]
