# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('category', models.CharField(choices=[('0', 'REIT'), ('1', 'BioTech'), ('2', 'Tech'), ('3', 'Crypto')], max_length=1, primary_key=True, serialize=False)),
                ('net_asset_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cash_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('BTC_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ETH_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('LTC_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('investment_value', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FundDividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateTimeField()),
                ('currency', models.CharField(choices=[('0', 'BTC'), ('1', 'ETH'), ('2', 'LTC')], max_length=1)),
                ('dividend_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='FundInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=75)),
                ('amount_invested', models.DecimalField(decimal_places=3, max_digits=12)),
                ('investment_date', models.DateTimeField()),
                ('fund_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='UserDividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('0', 'BTC'), ('1', 'ETH'), ('2', 'LTC')], max_length=1)),
                ('dividend_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dividend_date', models.DateTimeField()),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('0', 'BTC'), ('1', 'ETH'), ('2', 'LTC')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateTimeField()),
                ('fund_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.Fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
