# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20171204_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='BTC_amount',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
