# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20171204_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddividend',
            name='payee',
            field=models.ForeignKey(default='default fund', on_delete=django.db.models.deletion.CASCADE, related_name='Fund', to='landing_page.Fund'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='wallet',
            field=models.CharField(default='000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='funddividend',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Business', to='landing_page.FundInvestment'),
        ),
    ]
