# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 21:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20171204_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
