# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_auto_20171205_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
