# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_auto_20171205_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddividend',
            name='currency',
            field=models.CharField(choices=[('0', 'BTC'), ('1', 'ETH'), ('2', 'LTC'), ('3', 'USD')], max_length=1),
        ),
    ]
