# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_auto_20171206_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddividend',
            name='dividend_date',
            field=models.DateField(),
        ),
    ]
